country: china
provice: beijing
city: beijing
area: haidian

port: 8080

party: true

birthday: 1949-10-1

user:
  name: itcast
  age: 16

user2:
  name: itheima
  age: 17

a:
  b:
    c:
      d:
        f: 123

likes:
  - gaem
  - music
  - sleep

likes2: [game,music,sleep]

users:
  - name: zhangsan
    age: 18
  - name: lisi
    age: 20

users3: [{name: zhangsan,age: 18},{name: lisi, age: 17}]

users2:
  -
    name: zhangsan
    age: 18

  -
    name: lisi
    age: 20

baseDir: c:\windows

#使用${属性名}引用数据
tempDir: ${baseDir}\temp
#使用引号包裹的字符串，其中的转义字符可以生效
tempDir2: "${baseDir}\temp \t1 \t2 \t3"

# 创建类,用于封装下面的数据
# 由spring带我们去加载数据到对象中,一定要告诉spring加载这组信息
# 使用时候从spring中直接获取信息使用

datasorce:
  driver: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost/springboot_db
  username: root
  password: hsp

server:
  port: 80
  servlet:
    context-path: /test123

