-- 创建测试表 演员表

CREATE TABLE actor (-- 演员表)
 id INT PRIMARY KEY AUTO_INCREMENT,
 NAME VARCHAR(32) NOT NULL DEFAULT '',
 sex CHAR(1) NOT NULL DEFAULT '女',
 borndate DATETIME,
 phone VARCHAR(32));
 
 SELECT * FROM actor
 
 -- 增加2条记录,用于测试ResultSet
 INSERT INTO actor
	VALUES(NULL, '刘德华', '男', '1970-11-11', '110' );
	
CREATE TABLE ACCOUNT(
	id INT PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(32) NOT NULL DEFAULT '',
	balance DOUBLE NOT NULL DEFAULT 0) CHARACTER SET utf8;
	
INSERT INTO ACCOUNT VALUES(NULL, '马云', 3000);
INSERT INTO ACCOUNT VALUES(NULL, '马化腾', 10000);

SELECT * FROM ACCOUNT

-- 创建测试表
CREATE TABLE admin2
(id INT PRIMARY KEY AUTO_INCREMENT,
username VARCHAR(32) NOT NULL, 
PASSWORD VARCHAR(32) NOT NULL);

SELECT COUNT(*) FROM admin2
DROP TABLE admin2

