CREATE DATABASE p2p;
USE p2p;

CREATE TABLE `user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) DEFAULT NULL,
  `password` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `product`;

CREATE TABLE `product` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `proNum` VARCHAR(20) DEFAULT NULL,
  `proName` VARCHAR(20) DEFAULT NULL,
  `proLimit` INT(11) DEFAULT NULL,
  `annualized` DOUBLE DEFAULT NULL,
  `releaseDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `account`;

CREATE TABLE `account` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `total` DOUBLE DEFAULT NULL,
  `balance` DOUBLE DEFAULT NULL,
  `interest` DOUBLE DEFAULT NULL,
  `c_id` INT(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `c_id` (`c_id`),
  CONSTRAINT `account_ibfk_1` FOREIGN KEY (`c_id`) REFERENCES `customer` (`id`)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `product_account`;

CREATE TABLE `product_account` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `pa_num` VARCHAR(20) DEFAULT NULL,
  `pa_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `c_id` INT(11) DEFAULT NULL,
  `p_id` INT(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `c_id` (`c_id`),
  KEY `p_id` (`p_id`),
  CONSTRAINT `product_account_ibfk_1` FOREIGN KEY (`c_id`) REFERENCES `customer` (`id`),
  CONSTRAINT `product_account_ibfk_2` FOREIGN KEY (`p_id`) REFERENCES `product` (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;


CREATE TABLE `customer` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `c_name` VARCHAR(20) DEFAULT NULL,
  `email` VARCHAR(50) DEFAULT NULL,
  `email_status` INT(11) DEFAULT NULL,
  `password` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;


INSERT INTO USER VALUES(NULL,'tom','123');

SELECT * FROM product;

INSERT INTO product VALUES(NULL,'cz001','黑马一号',24,6.5,NULL);
INSERT INTO product VALUES(NULL,'cz002','黑马二号',12,4.5,NULL);
INSERT INTO product VALUES(NULL,'cz003','黑马三号',18,4.8,NULL);
INSERT INTO product VALUES(NULL,'cz004','黑马四号',20,5.2,NULL);

SELECT * FROM customer;
SELECT * FROM ACCOUNT;

UPDATE customer SET PASSWORD=MD5('123');

SELECT * FROM product_account;
SELECT * FROM ACCOUNT;

ALTER TABLE product_account ADD money DOUBLE;
ALTER TABLE product_account ADD interest DOUBLE;